# Codecov configuration for combined frontend coverage reporting
# Validated by Codecov VS Code extension and Codecov servers

codecov:
  token: 9bd746a5-c09e-4963-9c97-ab0b04839fe3

coverage:
  # Coverage gates: informational only (non-blocking)
  # Hard gates enabled later after lint/typecheck/build are stable + smoke tests in place
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 10%
    patch:
      default:
        informational: true
        target: auto
        threshold: 10%

  # Notify about coverage changes
  notify:
    require_ci_to_pass: false
    after_n_builds: 2

  # Automated alerts and reporting
  automation:
    # Create GitHub issues for coverage regressions
    github_issue:
      enabled: true
      threshold: -5% # Issue if coverage drops >5%
      close_on_improvement: true

    # Automated notifications
    notifications:
      email: true
      slack: false # Enable when Slack webhook configured

# PR comment settings with Codecov AI
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  after_n_builds: 2 # Wait for both frontend and backend builds

# Codecov AI - Automated insights and recommendations
ai:
  enabled: true
  # AI will analyze coverage changes and provide:
  # - Risk assessment for uncovered code
  # - Suggestions for test improvements
  # - Coverage trends and patterns
  # - Automated code review comments

  # Proactive monitoring
  behavior:
    # Post comments even without user activity
    default_comment_behavior: always
    # Notify on significant coverage changes
    notify_on_coverage_change: true
    # Weekly coverage summary
    weekly_report: true

# Ignore paths that should not affect coverage gates
ignore:
  - 'e2e/**'
  - 'infra/**'
  - 'helm/**'
  - 'k8s/**'
  - 'docs/**'
  - 'public/**'
  - 'scripts/**'

# Flags allow per-suite stats (frontend + backend)
flags:
  frontend:
    paths:
      - 'src/'
  backend:
    paths:
      - 'backend/app/'
